# application.yml
spring:
  datasource:
    url: jdbc:mysql://106.14.187.2:3306/agile-test-manager-service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 7414
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      defaultZone: http://106.14.187.2:8000/eureka/
    registryFetchIntervalSeconds: 10
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
services:
  attachment:
    url: example.com
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
