#spring:
#  sleuth:
#    integration:
#      enabled: false
#    scheduled:
#      enabled: false
#    sampler:
#      percentage: 1.0
spring:
  datasource:
    url: jdbc:mysql://106.14.187.2:3306/devops-service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 7414
  cloud:
    inetutils:
      #忽略回环网卡
      #      ignored-interfaces[0]: lo#选择的网段
      preferredNetworks[0]: 171
gitlab:
  url: "http://127.0.0.1:10080"
  privateToken: "Dm3dPtVKPGhm28Z-yuy_"
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://106.14.187.2:8000/eureka/
    registryFetchIntervalSeconds: 1
feign:
  hystrix:
    shareSecurityContext: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 50000